### ISSUE TITLE
start-gitlab.sh fails with GitLab 11.9

### ISSUE THREAD

**Issue by matejvelikonja** [terraform-providers/terraform-provider-gitlab#110]
Looks like GitLab 11.9 introduced some changes regarding token creation and because of that the following script fails.

https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/scripts/start-gitlab.sh

### Terraform Version
All

### Affected Resource(s)
All acceptance tests.

### Debug Output
```bash
echo 'PersonalAccessToken.create(user_id: 1, scopes: [:api, :read_user], name: :terraform, token: :ACCTEST).save!' | docker exec -i gitlab gitlab-rails console
-------------------------------------------------------------------------------------
 GitLab:       11.9.0 (a47124c)
 GitLab Shell: 8.7.1
 postgresql:   9.6.11
-------------------------------------------------------------------------------------
Loading production environment (Rails 5.0.7.1)
Switch to inspect mode.
PersonalAccessToken.create(user_id: 1, scopes: [:api, :read_user], name: :terraform, token: :ACCTEST).save!
Traceback (most recent call last):
       16: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:78:in `console'
       15: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/railties-5.0.7.1/lib/rails/commands/console_helper.rb:9:in `start'
       14: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/railties-5.0.7.1/lib/rails/commands/console.rb:65:in `start'
       13: from (irb):1
       12: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.1/lib/active_record/persistence.rb:33:in `create'
       11: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.1/lib/active_record/inheritance.rb:65:in `new'
       10: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.1/lib/active_record/inheritance.rb:65:in `new'
        9: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.1/lib/active_record/core.rb:319:in `initialize'
        8: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:36:in `assign_attributes'
        7: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:28:in `perform_attribute_assignment'
        6: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.1/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
        5: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.1/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
        4: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.1/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
        3: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.1/lib/active_model/attribute_assignment.rb:39:in `each'
        2: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.1/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
        1: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.1/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
ActiveModel::UnknownAttributeError (unknown attribute 'token' for PersonalAccessToken.)
```

### Expected Behavior
The code should work.

### Actual Behavior
The script fails.

### Steps to Reproduce
Run `scripts/start-gitlab.sh`

### References
https://gitlab.com/gitlab-org/gitlab-ce/commit/6d92a3d4e232d4137f66773c82f01c32d7474a21

**Comment by matejvelikonja** [comment]
@roidelapluie do you know how to fix this?

**Comment by roidelapluie** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/commit/ea283bbc6bc5d1e4b03259495c7e0e1e1978059e

They have fixed it in master it seems

**Comment by matejvelikonja** [comment]
@roidelapluie Looks like this is still broken in GitLab version `11.10.1`, even though the mentioned fix is in the code.

https://gitlab.com/gitlab-org/gitlab-ce/blob/v11.10.1/app/models/personal_access_token.rb

```
-------------------------------------------------------------------------------------
 GitLab:       11.10.1 (861fe405571)
 GitLab Shell: 9.0.0
 PostgreSQL:   9.6.11
-------------------------------------------------------------------------------------
Loading production environment (Rails 5.0.7.2)
Switch to inspect mode.
PersonalAccessToken.create(user_id: 1, scopes: [:api, :read_user], name: :terraform, token: :ACCTEST).save!
Traceback (most recent call last):
       16: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
       15: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
       14: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
       13: from (irb):1
       12: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/persistence.rb:33:in `create'
       11: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/inheritance.rb:65:in `new'
       10: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/inheritance.rb:65:in `new'
        9: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/core.rb:319:in `initialize'
        8: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:36:in `assign_attributes'
        7: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:28:in `perform_attribute_assignment'
        6: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
        5: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
        4: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
        3: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:39:in `each'
        2: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
        1: from /opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/activemodel-5.0.7.2/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
ActiveModel::UnknownAttributeError (unknown attribute 'token' for PersonalAccessToken.)
```

**Comment by roidelapluie** [comment]
Hello, #118 is ready for review
